name: Merge JSON Files

on:
  schedule:
    - cron: "0 0 * * *" # 매일 00:00에 실행
  push:
    branches:
      - main # main 브랜치에 머지될 때 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run merge script
        run: node merge.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with GitHub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Commit and push changes
        run: |
          git config --global user.name "jjackban"
          git config --global user.email "ban@baerae.com"
          git add URI/merged.json
          git commit -m "Auto-merge JSON files" || echo "No changes to commit"
          git push
